import type { DishDetail, Ingredient, Step } from '@features/dish/types';
import type { VoteRoom } from '@features/vote/types';

// ---------- DISHES ----------

function makeIngredients(
  dishId: string,
  items: [string, number | null, string | null][],
): Ingredient[] {
  return items.map(([name, amount, unit], i) => ({
    id: `${dishId}-ing-${i}`,
    dishId,
    name,
    amount,
    unit,
    isOptional: false,
    sortOrder: i + 1,
  }));
}

function makeSteps(dishId: string, instructions: string[], tips?: (string | null)[]): Step[] {
  return instructions.map((instruction, i) => ({
    id: `${dishId}-step-${i}`,
    dishId,
    stepNumber: i + 1,
    instruction,
    imageUrl: null,
    timerSecs: null,
    tip: tips?.[i] ?? null,
  }));
}

export const MOCK_DISHES: DishDetail[] = [
  {
    id: 'dish-1',
    name: 'Phở Bò Hà Nội',
    slug: 'pho-bo-ha-noi',
    description: 'Phở bò truyền thống Hà Nội với nước dùng trong, thơm mùi quế hồi.',
    imageUrl: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=800&h=600&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=400&h=300&fit=crop',
    category: 'bun_pho',
    difficulty: 3,
    prepTime: 30,
    cookTime: 180,
    servings: 4,
    costMin: 40000,
    costMax: 60000,
    spiceLevel: 1,
    tags: ['truyền thống', 'miền Bắc', 'nước dùng'],
    dietary: [],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    ingredients: makeIngredients('dish-1', [
      ['Xương bò', 1, 'kg'],
      ['Bánh phở tươi', 500, 'g'],
      ['Thịt bò tái', 300, 'g'],
      ['Hành tây', 2, 'củ'],
      ['Gừng', 1, 'nhánh'],
      ['Quế', 2, 'thanh'],
      ['Hoa hồi', 3, 'cánh'],
      ['Nước mắm', 3, 'thìa'],
      ['Hành lá', 1, 'bó'],
      ['Rau mùi', 1, 'bó'],
    ]),
    steps: makeSteps(
      'dish-1',
      [
        'Chần xương bò qua nước sôi, rửa sạch để loại bỏ bọt bẩn.',
        'Nướng hành tây và gừng trên bếp cho thơm, cạo sạch vỏ cháy.',
        'Cho xương vào nồi với 3 lít nước, nấu sôi rồi hạ lửa nhỏ, hầm 3 tiếng.',
        'Sau 1 tiếng, cho quế, hoa hồi, hành nướng, gừng nướng vào nồi.',
        'Nêm nước mắm, muối, đường cho vừa ăn. Lọc nước dùng.',
        'Chần bánh phở qua nước sôi, xếp vào tô.',
        'Thái thịt bò tái mỏng, xếp lên phở. Chan nước dùng nóng.',
        'Rắc hành lá, rau mùi. Ăn kèm chanh, ớt, giá đỗ, rau quế.',
      ],
      [
        'Chần kỹ để nước dùng trong hơn.',
        'Nướng cháy sơ giúp nước dùng thơm đặc trưng.',
        'Hầm lửa nhỏ liu riu, không đậy nắp.',
        null,
        'Nêm nhạt hơn vì sẽ thêm nước mắm khi ăn.',
        'Chần nhanh 10 giây thôi, phở sẽ mềm khi chan nước nóng.',
        'Thịt bò tái sẽ chín khi gặp nước dùng nóng.',
        null,
      ],
    ),
  },
  {
    id: 'dish-2',
    name: 'Bún Chả Hà Nội',
    slug: 'bun-cha-ha-noi',
    description: 'Bún chả với thịt nướng than hoa, nước mắm chua ngọt và rau sống.',
    imageUrl: 'https://images.unsplash.com/photo-1576577445504-6af96477db52?w=800&h=600&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1576577445504-6af96477db52?w=400&h=300&fit=crop',
    category: 'bun_pho',
    difficulty: 2,
    prepTime: 20,
    cookTime: 30,
    servings: 4,
    costMin: 35000,
    costMax: 50000,
    spiceLevel: 0,
    tags: ['nướng', 'miền Bắc', 'bún'],
    dietary: [],
    createdAt: '2024-01-02T00:00:00Z',
    updatedAt: '2024-01-02T00:00:00Z',
    ingredients: makeIngredients('dish-2', [
      ['Thịt ba chỉ', 500, 'g'],
      ['Thịt nạc vai xay', 300, 'g'],
      ['Bún tươi', 600, 'g'],
      ['Nước mắm', 4, 'thìa'],
      ['Đường', 3, 'thìa'],
      ['Giấm', 2, 'thìa'],
      ['Tỏi băm', 2, 'thìa'],
      ['Rau sống tổng hợp', 1, 'đĩa'],
    ]),
    steps: makeSteps('dish-2', [
      'Thái thịt ba chỉ miếng vừa, ướp với nước mắm, đường, tỏi, tiêu trong 30 phút.',
      'Thịt xay nặn thành từng viên nhỏ dẹt, ướp cùng gia vị.',
      'Pha nước chấm: nước mắm, đường, giấm, nước ấm, tỏi ớt băm.',
      'Nướng thịt trên bếp than hoặc lò nướng đến khi chín vàng, thơm.',
      'Luộc bún, xả nước lạnh cho ráo.',
      'Bày bún ra đĩa, thịt nướng vào bát nước chấm. Ăn kèm rau sống.',
    ]),
  },
  {
    id: 'dish-3',
    name: 'Cơm Tấm Sườn Bì Chả',
    slug: 'com-tam-suon-bi-cha',
    description: 'Cơm tấm Sài Gòn đầy đủ với sườn nướng, bì, chả trứng.',
    imageUrl: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&h=600&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=400&h=300&fit=crop',
    category: 'com',
    difficulty: 3,
    prepTime: 40,
    cookTime: 45,
    servings: 4,
    costMin: 30000,
    costMax: 45000,
    spiceLevel: 0,
    tags: ['miền Nam', 'cơm', 'nướng'],
    dietary: [],
    createdAt: '2024-01-03T00:00:00Z',
    updatedAt: '2024-01-03T00:00:00Z',
    ingredients: makeIngredients('dish-3', [
      ['Sườn heo', 600, 'g'],
      ['Gạo tấm', 400, 'g'],
      ['Da heo (bì)', 200, 'g'],
      ['Trứng', 4, 'quả'],
      ['Thịt xay', 200, 'g'],
      ['Nước mắm', 3, 'thìa'],
      ['Mỡ hành', 2, 'thìa'],
      ['Đồ chua', 1, 'bát'],
    ]),
    steps: makeSteps('dish-3', [
      'Ướp sườn với sả, tỏi, nước mắm, đường, dầu hào, mật ong trong 2 giờ.',
      'Nấu cơm tấm bằng gạo tấm, nước hơi ít hơn cơm thường.',
      'Luộc da heo, thái sợi nhỏ trộn với thính gạo làm bì.',
      'Trộn thịt xay, trứng, mộc nhĩ, miến. Hấp chả 30 phút.',
      'Nướng sườn trên bếp than, phết mỡ hành liên tục.',
      'Bày cơm, sườn, bì, chả ra đĩa. Rưới mỡ hành, kèm đồ chua, nước mắm.',
    ]),
  },
  {
    id: 'dish-4',
    name: 'Gỏi Cuốn Tôm Thịt',
    slug: 'goi-cuon-tom-thit',
    description: 'Gỏi cuốn tươi mát với tôm, thịt heo, bún và rau sống.',
    imageUrl: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=800&h=600&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=400&h=300&fit=crop',
    category: 'salad',
    difficulty: 1,
    prepTime: 20,
    cookTime: 10,
    servings: 4,
    costMin: 25000,
    costMax: 40000,
    spiceLevel: 0,
    tags: ['miền Nam', 'khai vị', 'nhẹ nhàng'],
    dietary: [],
    createdAt: '2024-01-04T00:00:00Z',
    updatedAt: '2024-01-04T00:00:00Z',
    ingredients: makeIngredients('dish-4', [
      ['Tôm sú', 300, 'g'],
      ['Thịt ba chỉ luộc', 200, 'g'],
      ['Bánh tráng', 12, 'miếng'],
      ['Bún tươi', 200, 'g'],
      ['Xà lách', 1, 'bó'],
      ['Rau thơm', 1, 'bó'],
      ['Tương đậu phộng', 100, 'ml'],
    ]),
    steps: makeSteps('dish-4', [
      'Luộc tôm, bóc vỏ, bổ đôi. Luộc thịt, thái lát mỏng.',
      'Nhúng bánh tráng vào nước ấm cho mềm.',
      'Đặt rau sống, bún, thịt, tôm lên bánh tráng.',
      'Cuốn chặt tay, gấp mép hai bên vào giữa.',
      'Pha tương đậu phộng: tương hột, tương đen, đậu phộng rang.',
      'Chấm gỏi cuốn với tương đậu phộng.',
    ]),
  },
  {
    id: 'dish-5',
    name: 'Lẩu Thái Tom Yum',
    slug: 'lau-thai-tom-yum',
    description: 'Lẩu chua cay kiểu Thái với tôm, nấm và sả chanh.',
    imageUrl: 'https://images.unsplash.com/photo-1548943487-a2e4e43b4853?w=800&h=600&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1548943487-a2e4e43b4853?w=400&h=300&fit=crop',
    category: 'lau',
    difficulty: 2,
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    costMin: 60000,
    costMax: 90000,
    spiceLevel: 3,
    tags: ['cay', 'hải sản', 'Thái'],
    dietary: [],
    createdAt: '2024-01-05T00:00:00Z',
    updatedAt: '2024-01-05T00:00:00Z',
    ingredients: makeIngredients('dish-5', [
      ['Tôm sú', 500, 'g'],
      ['Nấm rơm', 200, 'g'],
      ['Sả', 3, 'cây'],
      ['Lá chanh', 5, 'lá'],
      ['Ớt hiểm', 5, 'trái'],
      ['Nước cốt chanh', 3, 'thìa'],
      ['Nước mắm', 2, 'thìa'],
      ['Cà chua', 3, 'trái'],
      ['Nấm đông cô', 100, 'g'],
    ]),
    steps: makeSteps('dish-5', [
      'Đập dập sả, xé lá chanh. Cắt nấm, cà chua.',
      'Đun sôi 1.5 lít nước, cho sả, lá chanh, galangal vào.',
      'Thêm nấm, cà chua, nấu 5 phút.',
      'Cho tôm vào nấu đến khi chín hồng (2-3 phút).',
      'Nêm nước mắm, nước cốt chanh, ớt. Điều chỉnh chua cay vừa ăn.',
      'Tắt bếp, rắc rau mùi. Dùng nóng.',
    ]),
  },
  {
    id: 'dish-6',
    name: 'Bánh Mì Thịt Nướng',
    slug: 'banh-mi-thit-nuong',
    description: 'Bánh mì Việt Nam giòn rụm kẹp thịt nướng, đồ chua và rau thơm.',
    imageUrl: 'https://images.unsplash.com/photo-1600688640154-9619e002df30?w=800&h=600&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1600688640154-9619e002df30?w=400&h=300&fit=crop',
    category: 'other',
    difficulty: 1,
    prepTime: 15,
    cookTime: 15,
    servings: 2,
    costMin: 15000,
    costMax: 25000,
    spiceLevel: 1,
    tags: ['nhanh', 'đường phố', 'nướng'],
    dietary: [],
    createdAt: '2024-01-06T00:00:00Z',
    updatedAt: '2024-01-06T00:00:00Z',
    ingredients: makeIngredients('dish-6', [
      ['Bánh mì', 2, 'ổ'],
      ['Thịt heo nạc', 300, 'g'],
      ['Đồ chua (cà rốt, củ cải)', 100, 'g'],
      ['Dưa leo', 1, 'trái'],
      ['Rau mùi', 1, 'nắm'],
      ['Pate', 2, 'thìa'],
      ['Nước tương', 2, 'thìa'],
    ]),
    steps: makeSteps('dish-6', [
      'Ướp thịt với sả, tỏi, nước mắm, đường 30 phút.',
      'Nướng thịt trên bếp hoặc chảo đến khi chín vàng.',
      'Nướng bánh mì giòn, xẻ dọc, phết pate.',
      'Kẹp thịt nướng, đồ chua, dưa leo, rau mùi.',
      'Rưới nước tương, ớt tùy thích.',
    ]),
  },
  {
    id: 'dish-7',
    name: 'Cá Kho Tộ',
    slug: 'ca-kho-to',
    description: 'Cá kho tộ đậm đà trong nồi đất, vị ngọt từ nước dừa và caramel.',
    imageUrl: 'https://images.unsplash.com/photo-1626804475297-41608ea09aeb?w=800&h=600&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1626804475297-41608ea09aeb?w=400&h=300&fit=crop',
    category: 'com',
    difficulty: 2,
    prepTime: 15,
    cookTime: 45,
    servings: 4,
    costMin: 35000,
    costMax: 55000,
    spiceLevel: 1,
    tags: ['miền Nam', 'kho', 'cơm'],
    dietary: [],
    createdAt: '2024-01-07T00:00:00Z',
    updatedAt: '2024-01-07T00:00:00Z',
    ingredients: makeIngredients('dish-7', [
      ['Cá lóc (hoặc cá basa)', 600, 'g'],
      ['Nước dừa tươi', 200, 'ml'],
      ['Nước mắm', 3, 'thìa'],
      ['Đường thắng (caramel)', 2, 'thìa'],
      ['Tiêu', 1, 'thìa'],
      ['Hành tím', 3, 'củ'],
      ['Ớt', 2, 'trái'],
      ['Tỏi', 3, 'tép'],
    ]),
    steps: makeSteps('dish-7', [
      'Cá rửa sạch, cắt khúc, ướp nước mắm, tiêu 15 phút.',
      'Thắng đường thành caramel vàng nâu.',
      'Phi thơm hành tím, tỏi. Cho cá vào xào sơ.',
      'Đổ nước dừa vào, thêm caramel, nêm nước mắm.',
      'Kho lửa nhỏ 40 phút cho cá thấm và nước sệt lại.',
      'Rắc tiêu, ớt thái. Ăn nóng với cơm trắng.',
    ]),
  },
  {
    id: 'dish-8',
    name: 'Gà Xào Sả Ớt',
    slug: 'ga-xao-sa-ot',
    description: 'Gà xào giòn thơm lừng sả, cay nồng ớt, ăn kèm cơm nóng.',
    imageUrl: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800&h=600&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=400&h=300&fit=crop',
    category: 'xao',
    difficulty: 1,
    prepTime: 15,
    cookTime: 20,
    servings: 3,
    costMin: 30000,
    costMax: 45000,
    spiceLevel: 2,
    tags: ['nhanh', 'cay', 'xào'],
    dietary: [],
    createdAt: '2024-01-08T00:00:00Z',
    updatedAt: '2024-01-08T00:00:00Z',
    ingredients: makeIngredients('dish-8', [
      ['Đùi gà', 500, 'g'],
      ['Sả', 4, 'cây'],
      ['Ớt tươi', 3, 'trái'],
      ['Tỏi', 4, 'tép'],
      ['Nước mắm', 2, 'thìa'],
      ['Đường', 1, 'thìa'],
      ['Dầu ăn', 3, 'thìa'],
    ]),
    steps: makeSteps('dish-8', [
      'Gà rửa sạch, chặt miếng vừa. Ướp nước mắm, đường, tiêu.',
      'Sả thái lát mỏng. Ớt, tỏi băm nhỏ.',
      'Phi thơm sả, tỏi với dầu nóng.',
      'Cho gà vào xào lửa lớn đến khi se mặt.',
      'Thêm ớt, đảo đều. Nêm lại cho vừa ăn.',
      'Xào thêm 5 phút đến khi gà chín vàng, nước cạn. Rắc tiêu.',
    ]),
  },
  {
    id: 'dish-9',
    name: 'Chè Bưởi',
    slug: 'che-buoi',
    description: 'Chè bưởi mát lạnh với cùi bưởi dẻo, nước cốt dừa béo ngậy.',
    imageUrl: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=800&h=600&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400&h=300&fit=crop',
    category: 'trang_mieng',
    difficulty: 2,
    prepTime: 30,
    cookTime: 20,
    servings: 6,
    costMin: 15000,
    costMax: 25000,
    spiceLevel: 0,
    tags: ['tráng miệng', 'mát', 'dừa'],
    dietary: ['Chay'],
    createdAt: '2024-01-09T00:00:00Z',
    updatedAt: '2024-01-09T00:00:00Z',
    ingredients: makeIngredients('dish-9', [
      ['Cùi bưởi', 300, 'g'],
      ['Đường', 150, 'g'],
      ['Nước cốt dừa', 400, 'ml'],
      ['Bột năng', 2, 'thìa'],
      ['Đậu xanh cà', 100, 'g'],
      ['Lá dứa', 3, 'lá'],
    ]),
    steps: makeSteps('dish-9', [
      'Cùi bưởi bóc sợi, ngâm nước vôi trong 2 giờ cho dẻo.',
      'Rửa sạch cùi bưởi, vắt ráo. Luộc với lá dứa 10 phút.',
      'Nấu đậu xanh chín nhừ, nghiền mịn.',
      'Nấu nước đường với lá dứa, cho cùi bưởi vào rim 15 phút.',
      'Pha nước cốt dừa với bột năng, nấu sệt.',
      'Múc chè ra bát, rưới nước cốt dừa. Ăn nóng hoặc lạnh.',
    ]),
  },
  {
    id: 'dish-10',
    name: 'Mì Xào Hải Sản',
    slug: 'mi-xao-hai-san',
    description: 'Mì xào giòn với tôm, mực, rau cải thơm ngon.',
    imageUrl: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=800&h=600&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=400&h=300&fit=crop',
    category: 'xao',
    difficulty: 2,
    prepTime: 15,
    cookTime: 15,
    servings: 2,
    costMin: 35000,
    costMax: 55000,
    spiceLevel: 0,
    tags: ['hải sản', 'mì', 'nhanh'],
    dietary: [],
    createdAt: '2024-01-10T00:00:00Z',
    updatedAt: '2024-01-10T00:00:00Z',
    ingredients: makeIngredients('dish-10', [
      ['Mì trứng', 200, 'g'],
      ['Tôm sú', 200, 'g'],
      ['Mực ống', 150, 'g'],
      ['Cải ngọt', 200, 'g'],
      ['Cà rốt', 1, 'củ'],
      ['Nước tương', 2, 'thìa'],
      ['Dầu hào', 1, 'thìa'],
      ['Tỏi', 3, 'tép'],
    ]),
    steps: makeSteps('dish-10', [
      'Luộc mì al dente, xả nước lạnh, trộn chút dầu.',
      'Tôm bóc vỏ, mực khứa vân. Rau rửa sạch.',
      'Phi tỏi thơm, xào tôm mực lửa lớn đến chín tái. Bỏ ra.',
      'Xào rau cải nhanh, nêm chút muối.',
      'Cho mì vào chảo, thêm nước tương, dầu hào. Xào lửa lớn.',
      'Trộn hải sản, rau vào mì. Đảo đều, tắt bếp. Rắc tiêu.',
    ]),
  },
];

// ---------- VOTE ROOM ----------

export const MOCK_ROOM: VoteRoom = {
  id: 'room-demo',
  code: 'DEMO01',
  hostName: 'Minh',
  voteType: 'tournament',
  status: 'waiting',
  timerSecs: 60,
  dishes: MOCK_DISHES.slice(0, 8),
  participants: [
    { name: 'Minh', avatarColor: '#FF6B35', hasVoted: false },
    { name: 'Lan', avatarColor: '#E63946', hasVoted: false },
    { name: 'Hùng', avatarColor: '#FFB703', hasVoted: false },
  ],
  createdAt: '2024-01-01T00:00:00Z',
  expiresAt: '2024-12-31T23:59:59Z',
};
